all: 
	@javac -cp ../algs4.jar:../stdlib.jar SeamCarver.java ShowSeams.java ShowEnergy.java SCUtility.java ResizeDemo.java PrintSeams.java PrintEnergy.java
	@java -cp ../algs4.jar:../stdlib.jar:. PrintEnergy seamCarving/12x10.png

clean:
	rm *.class
